### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by NoozAbooz** [liuhh02/web-omr#17]
`  File "app.py", line 62, in <module>
    saver = tf.compat.v1.train.import_meta_graph(model)
  File "C:\Users\Michael\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\training\saver.py", line 1460, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "C:\Users\Michael\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\training\saver.py", line 1472, in _import_meta_graph_with_return_elements
    raise RuntimeError("Exporting/importing meta graphs is not supported when "
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.
`

**Comment by Aroueterra** [comment]
@mobilegmYT 
I'm guessing you have Tensorflow version 2+ installed?

You will need to disable eager execution for this to work, in addition to the compatibility with version 1.

Like so:

```
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
```

**Comment by NoozAbooz** [comment]
> @mobilegmYT
> I'm guessing you have Tensorflow version 2+ installed?
> 
> You will need to disable eager execution for this to work, in addition to the compatibility with version 1.
> 
> Like so:
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.compat.v1.disable_eager_execution()
> ```

I also got
```
Traceback (most recent call last):
  File "C:\Users\mobilegmYT\Downloads\web-omr-master\app.py", line 51, in <module>
    tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'
```

**Comment by Aroueterra** [comment]
Make sure that the line is using the compat.v1 alias. 

Did you try tf.compat.v1.reset_default_graph()?
